name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses : actions/upload-artifact@v3
      with :
       name: buildArtifact
       path: target/*war #build logunda path i görüyorsun
#burası optional o build fail edince sildik
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
  #  - name: Update dependency graph
   #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
  deploy:

    runs-on: ubuntu-latest
    needs : build #dependencies ekledi
    steps:
    - uses : actions/upload-artifact@v3
      with :
       name: buildArtifact
       
    - name: Deployment
      # run : echo "deployment Stage"
      run: |
       ls -alrt
       hostname
