name: Java CI with Maven

on:
  push:
    branches: [ "master" , "develop"]
  pull_request:
    branches: [ "master" ]
 # schedule: 
  #  - cron: "*/6 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses : actions/upload-artifact@v3
      with :
       name: buildArtifact
       path: target/*war 
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        context: .
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/planview:latest
